name: Kahlo Retreat
favicon: null
layout_spectrum: 0.1549191321246326
typography_spectrum: 0.780126313213259
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.19147738232277334
  lightness: 0.8992251725867391
  saturation: 0.42184171895496547
  rhythmicContrast: 0.3361209344584495
purpose: []
